version: '3'

x-app: &default-app
  build:
    context: "."
  volumes:
    - .:/app
  restart: "unless-stopped"

services:
  db:
    image: postgres
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=$POSTGRES_DB_NAME
      - POSTGRES_USER=$POSTGRES_DB_USER
      - POSTGRES_PASSWORD=$POSTGRES_DB_PASSWORD
  web:
    <<: *default-app
    command: bash -c "poetry run python manage.py migrate && poetry run gunicorn tuberank.wsgi --bind 0.0.0.0:8000 --timeout 600"
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=$POSTGRES_DB_NAME
      - POSTGRES_USER=$POSTGRES_DB_USER
      - POSTGRES_PASSWORD=$POSTGRES_DB_PASSWORD
      - DJANGO_SECRET_KEY=$DJANGO_SECRET_KEY
#   labels:
#     - "traefik.enable=true"
#     - "traefik.http.routers.tuberank.entrypoints=secure"
#     - "traefik.http.routers.tuberank.rule=Host(`tuberank.$DOMAIN`)"
#     - "traefik.http.services.tuberank.loadbalancer.server.port=8000"
#     - "traefik.http.routers.tuberank.tls.certresolver=le"

#etworks:
#   default:
#       name: $DEFAULT_NETWORK
