version: '3'

x-app: &default-app
  build:
    context: "."
    args:
      DOCKER_BUILDKIT: 1
  volumes:
    - .:/app
  restart: "unless-stopped"

services:
  web:
    <<: *default-app
    command: bash -c "npm run tailwind-build && poetry run python manage.py migrate && poetry run gunicorn tuberank.wsgi --bind 0.0.0.0:8000 --timeout 600"
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=$DATABASE_URL
      - YOUTUBE_DEVELOPER_KEY=$YOUTUBE_DEVELOPER_KEY
      - DJANGO_SECRET_KEY=$DJANGO_SECRET_KEY
      - DEBUG=$DEBUG
      - ALLOWED_HOSTS=$ALLOWED_HOSTS
      - CSRF_TRUSTED_ORIGINS=$CSRF_TRUSTED_ORIGINS
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.tuberank.entrypoints=secure"
      - "traefik.http.routers.tuberank.rule=Host(`tuberank.$DOMAIN`)"
      - "traefik.http.services.tuberank.loadbalancer.server.port=8000"
      - "traefik.http.routers.tuberank.tls.certresolver=le"

networks:
    default:
        name: $DEFAULT_NETWORK
