version: '3'

services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=$POSTGRES_DB_NAME
      - POSTGRES_USER=$POSTGRES_DB_USER
      - POSTGRES_PASSWORD=$POSTGRES_DB_PASSWORD
  web:
    container_name: ytvd
    build: .
    restart: always
    command: bash -c "poetry run python manage.py migrate && poetry run gunicorn ytvd.wsgi --bind 0.0.0.0:8000 --timeout 600"
    volumes:
      - .:/app
    environment:
      - POSTGRES_NAME=$POSTGRES_DB_NAME
      - POSTGRES_USER=$POSTGRES_DB_USER
      - POSTGRES_PASSWORD=$POSTGRES_DB_PASSWORD
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ytvd.entrypoints=secure"
      - "traefik.http.routers.ytvd.rule=Host(`$DOMAIN`)"
      - "traefik.http.services.ytvd.loadbalancer.server.port=8000"
      - "traefik.http.routers.ytvd.tls.certresolver=le"

networks:
    default:
        name: $DEFAULT_NETWORK
