# Generated by Django 4.2 on 2023-04-27 11:00

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Channel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("yt_id", models.CharField(max_length=24, unique=True)),
                (
                    "date_creation",
                    models.DateTimeField(verbose_name="date of channel creation"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Video",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("yt_id", models.CharField(max_length=11, unique=True)),
                (
                    "date_publication",
                    models.DateTimeField(verbose_name="date of video publication"),
                ),
                (
                    "channel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="videos",
                        to="ratings.channel",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VideoSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title_en", models.CharField(max_length=100)),
                ("count_views", models.IntegerField(blank=True, default=0, null=True)),
                ("count_likes", models.IntegerField(blank=True, default=0, null=True)),
                (
                    "count_comments",
                    models.IntegerField(blank=True, default=0, null=True),
                ),
                (
                    "date_creation",
                    models.DateTimeField(verbose_name="date of snapshot creation"),
                ),
                ("description", models.TextField(blank=True, max_length=5000)),
                ("thumbnail_url", models.CharField(max_length=100)),
                (
                    "video",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="snapshots",
                        to="ratings.video",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VideoRating",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rating",
                    models.PositiveIntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
                (
                    "date_publication",
                    models.DateTimeField(verbose_name="date of rating publication"),
                ),
                ("review_title", models.TextField(blank=True, max_length=100)),
                ("review_body", models.TextField(blank=True, max_length=5000)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="video_ratings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "video",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ratings",
                        to="ratings.video",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ChannelSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name_en", models.CharField(max_length=20)),
                (
                    "count_subscribers",
                    models.IntegerField(blank=True, default=0, null=True),
                ),
                ("count_views", models.IntegerField(blank=True, default=0, null=True)),
                ("count_videos", models.IntegerField(blank=True, default=0, null=True)),
                (
                    "date_creation",
                    models.DateTimeField(verbose_name="date of snapshot creation"),
                ),
                ("custom_url", models.CharField(max_length=24)),
                ("description", models.TextField(blank=True, max_length=5000)),
                ("thumbnail_url", models.CharField(max_length=100)),
                (
                    "channel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="snapshots",
                        to="ratings.channel",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ChannelRating",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rating",
                    models.PositiveIntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
                (
                    "date_publication",
                    models.DateTimeField(verbose_name="date of rating publication"),
                ),
                ("review_title", models.TextField(blank=True, max_length=100)),
                ("review_body", models.TextField(blank=True, max_length=5000)),
                (
                    "channel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ratings",
                        to="ratings.channel",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="channel_ratings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="videorating",
            constraint=models.UniqueConstraint(
                fields=("user", "video"), name="unique_user_rating_video"
            ),
        ),
        migrations.AddConstraint(
            model_name="channelrating",
            constraint=models.UniqueConstraint(
                fields=("user", "channel"), name="unique_user_rating_channel"
            ),
        ),
    ]
