# Generated by Django 4.2 on 2023-04-28 09:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ratings", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="channelsnapshot",
            name="custom_url",
            field=models.CharField(blank=True, max_length=24),
        ),
    ]
