# Generated by Django 4.2 on 2023-05-05 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("ratings", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="videolistitem",
            name="list",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="ratings.videolist",
            ),
        ),
        migrations.AddConstraint(
            model_name="videolistitem",
            constraint=models.UniqueConstraint(
                fields=("list", "order"), name="unique_order_in_list"
            ),
        ),
    ]
