# Generated by Django 4.2 on 2023-04-28 21:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ratings", "0002_alter_channelsnapshot_custom_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="channel",
            name="description",
            field=models.TextField(blank=True, max_length=5000),
        ),
    ]
