# Generated by Django 4.2 on 2023-05-05 10:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ratings", "0002_alter_videolistitem_list_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="videolistitem",
            old_name="order",
            new_name="rank",
        ),
    ]
