# Generated by Django 4.2 on 2023-04-30 16:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ratings", "0003_videolistrating_alter_usertag_name_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="videolist",
            constraint=models.UniqueConstraint(
                fields=("user", "name"), name="unique_user_video_list_by_name"
            ),
        ),
    ]
