# Generated by Django 4.2 on 2023-04-29 21:06

import django.core.validators
from django.db import migrations, models
import ratings.enums


class Migration(migrations.Migration):
    dependencies = [
        ("ratings", "0003_channel_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="channelrating",
            name="rating",
            field=models.PositiveIntegerField(
                choices=[
                    (ratings.enums.Rating["ZERO_STAR"], "0"),
                    (ratings.enums.Rating["ZERO_STAR_AND_HALF"], "0.5"),
                    (ratings.enums.Rating["ONE_STAR"], "1"),
                    (ratings.enums.Rating["ONE_STAR_AND_HALF"], "1.5"),
                    (ratings.enums.Rating["TWO_STARS"], "2"),
                    (ratings.enums.Rating["TWO_STARS_AND_HALF"], "2.5"),
                    (ratings.enums.Rating["THREE_STARS"], "3"),
                    (ratings.enums.Rating["THREE_STARS_AND_HALF"], "3.5"),
                    (ratings.enums.Rating["FOUR_STARS"], "4"),
                    (ratings.enums.Rating["FOUR_STARS_AND_HALF"], "4.5"),
                    (ratings.enums.Rating["FIVE_STARS"], "5"),
                ],
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(10),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="videorating",
            name="rating",
            field=models.PositiveIntegerField(
                choices=[
                    (ratings.enums.Rating["ZERO_STAR"], "0"),
                    (ratings.enums.Rating["ZERO_STAR_AND_HALF"], "0.5"),
                    (ratings.enums.Rating["ONE_STAR"], "1"),
                    (ratings.enums.Rating["ONE_STAR_AND_HALF"], "1.5"),
                    (ratings.enums.Rating["TWO_STARS"], "2"),
                    (ratings.enums.Rating["TWO_STARS_AND_HALF"], "2.5"),
                    (ratings.enums.Rating["THREE_STARS"], "3"),
                    (ratings.enums.Rating["THREE_STARS_AND_HALF"], "3.5"),
                    (ratings.enums.Rating["FOUR_STARS"], "4"),
                    (ratings.enums.Rating["FOUR_STARS_AND_HALF"], "4.5"),
                    (ratings.enums.Rating["FIVE_STARS"], "5"),
                ],
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(10),
                ],
            ),
        ),
    ]
