# Generated by Django 4.2 on 2023-04-29 21:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ratings", "0004_alter_channelrating_rating_alter_videorating_rating"),
    ]

    operations = [
        migrations.AlterField(
            model_name="channelrating",
            name="rating",
            field=models.PositiveIntegerField(
                choices=[
                    ("0", 0),
                    ("0.5", 1),
                    ("1", 2),
                    ("1.5", 3),
                    ("2", 4),
                    ("2.5", 5),
                    ("3", 6),
                    ("3.5", 7),
                    ("4", 8),
                    ("4.5", 9),
                    ("5", 10),
                ],
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(10),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="videorating",
            name="rating",
            field=models.PositiveIntegerField(
                choices=[
                    ("0", 0),
                    ("0.5", 1),
                    ("1", 2),
                    ("1.5", 3),
                    ("2", 4),
                    ("2.5", 5),
                    ("3", 6),
                    ("3.5", 7),
                    ("4", 8),
                    ("4.5", 9),
                    ("5", 10),
                ],
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(10),
                ],
            ),
        ),
    ]
