# Generated by Django 4.2 on 2023-04-30 19:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ratings", "0004_videolist_unique_user_video_list_by_name"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="videolistitem",
            constraint=models.UniqueConstraint(
                fields=("list", "video"), name="unique_video_in_list"
            ),
        ),
    ]
