# Generated by Django 4.2 on 2023-05-05 11:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ratings", "0004_remove_videolistitem_unique_order_in_list_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="videolistitem",
            name="description",
            field=models.TextField(blank=True, max_length=5000),
        ),
    ]
