# Generated by Django 4.2 on 2023-05-06 18:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ratings", "0007_alter_videosnapshot_count_views"),
    ]

    operations = [
        migrations.AlterField(
            model_name="channelsnapshot",
            name="thumbnail_url",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="videosnapshot",
            name="thumbnail_url",
            field=models.CharField(max_length=200),
        ),
    ]
