# Generated by Django 4.2 on 2023-05-06 19:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ratings", "0008_alter_channelsnapshot_thumbnail_url_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="channelrating",
            name="rating",
            field=models.PositiveIntegerField(
                choices=[
                    (0, "0"),
                    (1, "0.5"),
                    (2, "1"),
                    (3, "1.5"),
                    (4, "2"),
                    (5, "2.5"),
                    (6, "3"),
                    (7, "3.5"),
                    (8, "4"),
                    (9, "4.5"),
                    (10, "5"),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="channelsnapshot",
            name="name_en",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="usertag",
            name="state",
            field=models.PositiveIntegerField(
                choices=[(0, "In validation"), (1, "Validated")]
            ),
        ),
        migrations.AlterField(
            model_name="videorating",
            name="rating",
            field=models.PositiveIntegerField(
                choices=[
                    (0, "0"),
                    (1, "0.5"),
                    (2, "1"),
                    (3, "1.5"),
                    (4, "2"),
                    (5, "2.5"),
                    (6, "3"),
                    (7, "3.5"),
                    (8, "4"),
                    (9, "4.5"),
                    (10, "5"),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="videosnapshot",
            name="category",
            field=models.PositiveIntegerField(
                blank=True,
                choices=[
                    (1, "Film & Animation"),
                    (2, "Autos & Vehicles"),
                    (10, "Music"),
                    (15, "Pets & Animals"),
                    (17, "Sports"),
                    (19, "Travel & Events"),
                    (20, "Gaming"),
                    (22, "People & Blogs"),
                    (23, "Comedy"),
                    (24, "Entertainment"),
                    (25, "News & Politics"),
                    (26, "How-to & Styles"),
                    (27, "Education"),
                    (28, "Science & Technology"),
                    (29, "Non-profits & Activism"),
                ],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="videoviewing",
            name="state",
            field=models.PositiveIntegerField(choices=[(0, "Watching"), (1, "Viewed")]),
        ),
    ]
