# Generated by Django 4.2.1 on 2023-05-09 18:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("ratings", "0009_alter_channelrating_rating_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserTagVote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "vote",
                    models.IntegerField(choices=[(-1, "Downvote"), (1, "Upvote")]),
                ),
                (
                    "tag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="votes",
                        to="ratings.usertag",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "video",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="ratings.video"
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="usertagvote",
            constraint=models.UniqueConstraint(
                fields=("user", "tag", "video"), name="unique_vote_by_tag_user_video"
            ),
        ),
    ]
