# Generated by Django 4.2.1 on 2023-05-09 18:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ratings", "0010_usertagvote_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usertagvote",
            name="vote",
            field=models.IntegerField(choices=[(0, "Downvote"), (1, "Upvote")]),
        ),
    ]
