# Generated by Django 4.2.1 on 2023-05-12 10:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ratings", "0012_alter_usertag_name"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="videolistitem",
            name="unique_rank_in_list",
        ),
    ]
