# Generated by Django 4.2.14 on 2024-10-09 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ratings", "0014_alter_videoviewing_video"),
    ]

    operations = [
        migrations.AlterField(
            model_name="channelsnapshot",
            name="custom_url",
            field=models.CharField(blank=True, max_length=31),
        ),
    ]
